- hosts: router
  name: cleanup
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: saubermachen und namen setzten
      copy:
        src: /home/cumulus/HB/.cleanup/{{ inventory_hostname }}
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for all nodes
      shell:  nv config apply startup -y
      
      
- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/HB/.netplan/{{ inventory_hostname }}
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
      # danke netplan
